// Firebase configs
const FIREBASE_API_KEY = process.env.NEXT_PUBLIC_FIREBASE_API_KEY;

const FIREBASE_AUTH_DOMAIN = process.env.NEXT_PUBLIC_AUTH_DOMAIN;

const FIREBASE_PROJECT_ID = process.env.NEXT_PUBLIC_PROJECT_ID;

const FIREBASE_STORAGE_BUCKET = process.env.NEXT_PUBLIC_STORAGE_BUCKET;

const FIREBASE_MESSAGING_SENDER_ID =
  process.env.NEXT_PUBLIC_MESSAGING_SENDER_ID;

const FIREBASE_APP_ID = process.env.NEXT_PUBLIC_APP_ID;

const FIREBASE_MEASUREMENT_ID = process.env.NEXT_PUBLIC_MEASUREMENT_ID;

export {
  FIREBASE_API_KEY,
  FIREBASE_AUTH_DOMAIN,
  FIREBASE_PROJECT_ID,
  FIREBASE_STORAGE_BUCKET,
  FIREBASE_MEASUREMENT_ID,
  FIREBASE_MESSAGING_SENDER_ID,
  FIREBASE_APP_ID,
};
